[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Open Lab Neuroscienze Computazionali"
authors = [{name = "Gruppo Neuroscienze Computazionali UNICA", email = "golosio@unica.it"}]
dynamic = ["version", "description"]
